<a href="https://colab.research.google.com/github/AliArabi55/Algorithim-Task/blob/main/Copy_of_ML_Paper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **(3465, 210)**

In [112]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
# Load the data from the CSV file
df = pd.read_csv('/content/all-2175.csv')

In [92]:
# Display the first few rows of the dataframe
df.head()

,case_id,case_submitter_id,project_id,age_at_index,age_is_obfuscated,cause_of_death,cause_of_death_source,country_of_birth,country_of_residence_at_enrollment,days_to_birth,...,treatment_dose_units,treatment_duration,treatment_effect,treatment_effect_indicator,treatment_frequency,treatment_intent_type,treatment_or_therapy,treatment_outcome,treatment_outcome_duration,treatment_type
0,0014c2a8-850a-4305-a0d0-8a08b815a641,AD4306,FM-AD,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
1,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,'--,'--,'--,'--,'--,-17045,...,'--,'--,'--,'--,'--,'--,no,'--,'--,"Pharmaceutical Therapy, NOS"
2,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,'--,'--,'--,'--,'--,-17045,...,'--,'--,'--,'--,'--,'--,no,'--,'--,"Radiation Therapy, NOS"
3,001e8d94-7884-4320-80f4-dbbac349394b,AD8086,FM-AD,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
4,0020317d-d10e-4e75-8fa6-7c1bdcdee471,TCGA-HS-A5NA,TCGA-SARC,65,'--,'--,'--,'--,'--,-24025,...,'--,'--,'--,'--,'--,'--,yes,'--,'--,"Radiation Therapy, NOS"

### Number of rows and columns

In [93]:
print("Number of rows and columns:")
print(df.shape)

Number of rows and columns:
(3465, 210)

In [94]:
print("\nData types for each column:")
print(df.dtypes)

Data types for each column:
case_id                       object
case_submitter_id             object
project_id                    object
age_at_index                  object
age_is_obfuscated             object
                               ...
treatment_intent_type         object
treatment_or_therapy          object
treatment_outcome             object
treatment_outcome_duration    object
treatment_type                object
Length: 210, dtype: object

In [95]:
print(df.dtypes.value_counts())

object    210
Name: count, dtype: int64

In [96]:
# Data types and missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3465 entries, 0 to 3464
Columns: 210 entries, case_id to treatment_type
dtypes: object(210)
memory usage: 5.6+ MB

###Replace '--' with NaN

In [100]:
# Replace '--' with NaN
df.replace("'--", np.nan, inplace=True) # Use np.nan instead of pd.NAN

In [101]:
# Display the first few rows of the dataframe
df.head()

,case_id,case_submitter_id,project_id,age_at_index,age_is_obfuscated,cause_of_death,cause_of_death_source,country_of_birth,country_of_residence_at_enrollment,days_to_birth,...,treatment_dose_units,treatment_duration,treatment_effect,treatment_effect_indicator,treatment_frequency,treatment_intent_type,treatment_or_therapy,treatment_outcome,treatment_outcome_duration,treatment_type
0,0014c2a8-850a-4305-a0d0-8a08b815a641,AD4306,FM-AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,NaN,NaN,NaN,NaN,NaN,-17045,...,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,NaN,"Pharmaceutical Therapy, NOS"
2,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,NaN,NaN,NaN,NaN,NaN,-17045,...,NaN,NaN,NaN,NaN,NaN,NaN,no,NaN,NaN,"Radiation Therapy, NOS"
3,001e8d94-7884-4320-80f4-dbbac349394b,AD8086,FM-AD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0020317d-d10e-4e75-8fa6-7c1bdcdee471,TCGA-HS-A5NA,TCGA-SARC,65,NaN,NaN,NaN,NaN,NaN,-24025,...,NaN,NaN,NaN,NaN,NaN,NaN,yes,NaN,NaN,"Radiation Therapy, NOS"

###statistics for numerical columns

In [102]:
# Summary statistics for numerical columns
df.describe()

,cause_of_death_source,country_of_birth,country_of_residence_at_enrollment,education_level,marital_status,occupation_duration_years,premature_at_birth,weeks_gestation_at_birth,adrenal_hormone,ajcc_clinical_n,...,treatment_anatomic_sites,treatment_arm,treatment_dose,treatment_dose_max,treatment_dose_units,treatment_duration,treatment_effect,treatment_effect_indicator,treatment_frequency,treatment_outcome_duration
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
print("\nMissing values count:")
print(df.isnull().sum())

Missing values count:
case_id                          0
case_submitter_id                0
project_id                       0
age_at_index                  1020
age_is_obfuscated             3357
                              ...
treatment_intent_type         3404
treatment_or_therapy           970
treatment_outcome             3435
treatment_outcome_duration    3465
treatment_type                 982
Length: 210, dtype: int64

In [104]:
print("Number of rows and columns:")
print(df.shape)

# Assuming df_cleaned is your DataFrame
df_cleaned = df.drop_duplicates(subset=['case_id'], keep='first')

# Now df_cleaned contains only unique rows based on 'case_id'

print("Number of rows and columns:")
print(df_cleaned.shape)

Number of rows and columns:
(3465, 210)
Number of rows and columns:
(2175, 210)

In [105]:
# Get the count of missing values
missing_values = df_cleaned.isnull().sum()
total_rows = len(df_cleaned)  # Get the total number of rows

# Create a formatted output
print("\nMissing values count with percentage:")
print(f"{'Index':<6} {'Column Name':<50} {'Missing Values':<20} {'Percentage Missing':<20}")

# Display the count and percentage of missing values for each column
for index, column in enumerate(df_cleaned.columns):
    count_missing = missing_values[column]
    percentage_missing = (count_missing / total_rows) * 100  # Calculate percentage
    print(f"{index + 1:<6} {column:<50} {count_missing:<20} {percentage_missing:<20.2f}")

Missing values count with percentage:
Index  Column Name                                        Missing Values       Percentage Missing
1      case_id                                            0                    0.00
2      case_submitter_id                                  0                    0.00
3      project_id                                         0                    0.00
4      age_at_index                                       970                  44.60
5      age_is_obfuscated                                  2156                 99.13
6      cause_of_death                                     2139                 98.34
7      cause_of_death_source                              2175                 100.00
8      country_of_birth                                   2175                 100.00
9      country_of_residence_at_enrollment                 2175                 100.00
10     days_to_birth                                      741                  34.07
11     days_to_death                                      1664                 76.51
12     education_level                                    2175                 100.00
13     ethnicity                                          0                    0.00
14     gender                                             0                    0.00
15     marital_status                                     2175                 100.00
16     occupation_duration_years                          2175                 100.00
17     premature_at_birth                                 2175                 100.00
18     race                                               0                    0.00
19     vital_status                                       0                    0.00
20     weeks_gestation_at_birth                           2175                 100.00
21     year_of_birth                                      736                  33.84
22     year_of_death                                      1768                 81.29
23     adrenal_hormone                                    2175                 100.00
24     age_at_diagnosis                                   31                   1.43
25     ajcc_clinical_m                                    1943                 89.33
26     ajcc_clinical_n                                    2175                 100.00
27     ajcc_clinical_stage                                2175                 100.00
28     ajcc_clinical_t                                    2175                 100.00
29     ajcc_pathologic_m                                  1936                 89.01
30     ajcc_pathologic_n                                  1936                 89.01
31     ajcc_pathologic_stage                              1922                 88.37
32     ajcc_pathologic_t                                  1937                 89.06
33     ajcc_staging_system_edition                        1926                 88.55
34     ann_arbor_b_symptoms                               2169                 99.72
35     ann_arbor_b_symptoms_described                     2175                 100.00
36     ann_arbor_clinical_stage                           2174                 99.95
37     ann_arbor_extranodal_involvement                   2167                 99.63
38     ann_arbor_pathologic_stage                         2169                 99.72
39     best_overall_response                              2169                 99.72
40     burkitt_lymphoma_clinical_variant                  2168                 99.68
41     cancer_detection_method                            2175                 100.00
42     child_pugh_classification                          2175                 100.00
43     clark_level                                        2175                 100.00
44     classification_of_tumor                            240                  11.03
45     cog_liver_stage                                    2175                 100.00
46     cog_neuroblastoma_risk_group                       2175                 100.00
47     cog_renal_stage                                    2175                 100.00
48     cog_rhabdomyosarcoma_risk_group                    2175                 100.00
49     contiguous_organ_invaded                           2175                 100.00
50     days_to_best_overall_response                      2169                 99.72
51     days_to_diagnosis                                  981                  45.10
52     days_to_last_follow_up                             895                  41.15
53     days_to_last_known_disease_status                  1948                 89.56
54     days_to_recurrence                                 2160                 99.31
55     diagnosis_is_primary_disease                       2175                 100.00
56     double_expressor_lymphoma                          2175                 100.00
57     double_hit_lymphoma                                2175                 100.00
58     eln_risk_classification                            2175                 100.00
59     enneking_msts_grade                                2175                 100.00
60     enneking_msts_metastasis                           2175                 100.00
61     enneking_msts_stage                                2175                 100.00
62     enneking_msts_tumor_site                           2175                 100.00
63     ensat_clinical_m                                   2175                 100.00
64     ensat_pathologic_n                                 2175                 100.00
65     ensat_pathologic_stage                             2175                 100.00
66     ensat_pathologic_t                                 2175                 100.00
67     esophageal_columnar_dysplasia_degree               2175                 100.00
68     esophageal_columnar_metaplasia_present             2175                 100.00
69     fab_morphology_code                                2175                 100.00
70     figo_stage                                         766                  35.22
71     figo_staging_edition_year                          2175                 100.00
72     first_symptom_longest_duration                     2175                 100.00
73     first_symptom_prior_to_diagnosis                   2175                 100.00
74     gastric_esophageal_junction_involvement            2175                 100.00
75     gleason_grade_group                                2175                 100.00
76     gleason_grade_tertiary                             2175                 100.00
77     gleason_patterns_percent                           2175                 100.00
78     gleason_score                                      2175                 100.00
79     goblet_cells_columnar_mucosa_present               2175                 100.00
80     icd_10_code                                        969                  44.55
81     igcccg_stage                                       2175                 100.00
82     inpc_grade                                         2175                 100.00
83     inpc_histologic_group                              2175                 100.00
84     inrg_stage                                         2175                 100.00
85     inss_stage                                         2175                 100.00
86     international_prognostic_index                     2175                 100.00
87     irs_group                                          2175                 100.00
88     irs_stage                                          2175                 100.00
89     ishak_fibrosis_score                               2175                 100.00
90     iss_stage                                          2175                 100.00
91     last_known_disease_status                          19                   0.87
92     laterality                                         2174                 99.95
93     margin_distance                                    2175                 100.00
94     margins_involved_site                              2175                 100.00
95     masaoka_stage                                      2175                 100.00
96     max_tumor_bulk_site                                2175                 100.00
97     medulloblastoma_molecular_classification           2175                 100.00
98     melanoma_known_primary                             2175                 100.00
99     metastasis_at_diagnosis                            2171                 99.82
100    metastasis_at_diagnosis_site                       2175                 100.00
101    method_of_diagnosis                                2167                 99.63
102    micropapillary_features                            2175                 100.00
103    mitosis_karyorrhexis_index                         2175                 100.00
104    mitotic_count                                      2175                 100.00
105    morphology                                         0                    0.00
106    ovarian_specimen_status                            2174                 99.95
107    ovarian_surface_involvement                        2174                 99.95
108    papillary_renal_cell_type                          2175                 100.00
109    pediatric_kidney_staging                           2175                 100.00
110    peritoneal_fluid_cytological_status                2170                 99.77
111    pregnant_at_diagnosis                              2175                 100.00
112    primary_diagnosis                                  0                    0.00
113    primary_disease                                    2175                 100.00
114    primary_gleason_grade                              2175                 100.00
115    prior_malignancy                                   956                  43.95
116    prior_treatment                                    962                  44.23
117    progression_or_recurrence                          19                   0.87
118    residual_disease                                   1942                 89.29
119    satellite_nodule_present                           2175                 100.00
120    secondary_gleason_grade                            2175                 100.00
121    site_of_resection_or_biopsy                        0                    0.00
122    sites_of_involvement                               2175                 100.00
123    sites_of_involvement_count                         2175                 100.00
124    supratentorial_localization                        2175                 100.00
125    synchronous_malignancy                             966                  44.41
126    tissue_or_organ_of_origin                          0                    0.00
127    tumor_burden                                       2175                 100.00
128    tumor_confined_to_organ_of_origin                  2175                 100.00
129    tumor_depth                                        2175                 100.00
130    tumor_focality                                     1943                 89.33
131    tumor_grade                                        16                   0.74
132    tumor_grade_category                               2175                 100.00
133    tumor_regression_grade                             2175                 100.00
134    uicc_clinical_m                                    2175                 100.00
135    uicc_clinical_n                                    2175                 100.00
136    uicc_clinical_stage                                2175                 100.00
137    uicc_clinical_t                                    2175                 100.00
138    uicc_pathologic_m                                  2175                 100.00
139    uicc_pathologic_n                                  2175                 100.00
140    uicc_pathologic_stage                              2175                 100.00
141    uicc_pathologic_t                                  2175                 100.00
142    uicc_staging_system_edition                        2175                 100.00
143    ulceration_indicator                               2175                 100.00
144    weiss_assessment_findings                          2175                 100.00
145    weiss_assessment_score                             2175                 100.00
146    who_cns_grade                                      2175                 100.00
147    who_nte_grade                                      2175                 100.00
148    wilms_tumor_histologic_subtype                     2175                 100.00
149    year_of_diagnosis                                  739                  33.98
150    anaplasia_present                                  2175                 100.00
151    anaplasia_present_type                             2175                 100.00
152    breslow_thickness                                  2175                 100.00
153    circumferential_resection_margin                   2175                 100.00
154    greatest_tumor_dimension                           2175                 100.00
155    gross_tumor_weight                                 2175                 100.00
156    largest_extrapelvic_peritoneal_focus               2175                 100.00
157    lymph_node_involved_site                           2175                 100.00
158    lymph_nodes_positive                               2175                 100.00
159    lymph_nodes_tested                                 2175                 100.00
160    lymphatic_invasion_present                         2175                 100.00
161    non_nodal_regional_disease                         2175                 100.00
162    non_nodal_tumor_deposits                           2175                 100.00
163    percent_tumor_invasion                             2175                 100.00
164    perineural_invasion_present                        2175                 100.00
165    peripancreatic_lymph_nodes_positive                2175                 100.00
166    peripancreatic_lymph_nodes_tested                  2175                 100.00
167    transglottic_extension                             2175                 100.00
168    tumor_largest_dimension_diameter                   2175                 100.00
169    tumor_stage                                        2175                 100.00
170    vascular_invasion_present                          2175                 100.00
171    vascular_invasion_type                             2175                 100.00
172    chemo_concurrent_to_radiation                      2175                 100.00
173    clinical_trial_indicator                           2175                 100.00
174    course_number                                      2175                 100.00
175    days_to_treatment_end                              2166                 99.59
176    days_to_treatment_start                            2165                 99.54
177    drug_category                                      2175                 100.00
178    embolic_agent                                      2175                 100.00
179    initial_disease_status                             2169                 99.72
180    lesions_treated_number                             2175                 100.00
181    number_of_cycles                                   2172                 99.86
182    number_of_fractions                                2175                 100.00
183    prescribed_dose                                    2175                 100.00
184    protocol_identifier                                2175                 100.00
185    radiosensitizing_agent                             2175                 100.00
186    reason_treatment_ended                             2175                 100.00
187    reason_treatment_not_given                         2175                 100.00
188    regimen_or_line_of_therapy                         2175                 100.00
189    residual_disease.1                                 1942                 89.29
190    route_of_administration                            2175                 100.00
191    therapeutic_agents                                 2166                 99.59
192    therapeutic_level_achieved                         2175                 100.00
193    therapeutic_levels_achieved                        2175                 100.00
194    therapeutic_target_level                           2175                 100.00
195    timepoint_category                                 2175                 100.00
196    treatment_anatomic_site                            2175                 100.00
197    treatment_anatomic_sites                           2175                 100.00
198    treatment_arm                                      2175                 100.00
199    treatment_dose                                     2175                 100.00
200    treatment_dose_max                                 2175                 100.00
201    treatment_dose_units                               2175                 100.00
202    treatment_duration                                 2175                 100.00
203    treatment_effect                                   2175                 100.00
204    treatment_effect_indicator                         2175                 100.00
205    treatment_frequency                                2175                 100.00
206    treatment_intent_type                              2166                 99.59
207    treatment_or_therapy                               961                  44.18
208    treatment_outcome                                  2171                 99.82
209    treatment_outcome_duration                         2175                 100.00
210    treatment_type                                     962                  44.23

In [106]:
# Calculate missing value percentages
missing_percentage = (df_cleaned.isnull().sum() / len(df_cleaned)) * 100

# Count columns with >90% missing values
count_high_missing = len(missing_percentage[missing_percentage > 90])

# Print the count
print(f"Columns with >90% missing values: {count_high_missing}")

Columns with >90% missing values: 169

###display columns with more than 90% missing value

In [114]:
# Get the total number of rows
total_rows = len(df_cleaned)

# Calculate the percentage of missing values for each column
missing_percentage = (df_cleaned.isnull().sum() / total_rows) * 100

# Filter columns with more than 90% missing values
columns_above_90_missing = missing_percentage[missing_percentage > 90]

# Display columns with more than 90% missing values (starting index from 1)
print("\nColumns with more than 90% missing values:")
print(f"{'Index':<6} {'Column Name':<50} {'Percentage Missing':<20}")
for index, (column, percentage) in enumerate(columns_above_90_missing.items(), start=1):
    print(f"{index:<6} {column:<50} {percentage:<20.2f}")

Columns with more than 90% missing values:
Index  Column Name                                        Percentage Missing

#### Remove columns with more than 90% missing values

####We must make sure that the columns you will delete are not important.✅

In [131]:
# Remove columns with more than 90% missing values
df_cleaned = df_cleaned.drop(columns=columns_above_90_missing.index)

# Display confirmation
print(f"\nRemoved {len(columns_above_90_missing)} columns with more than 90% missing values.")

Removed 0 columns with more than 90% missing values.

###Display remaining columns after deletion

In [130]:
# Get the list of remaining columns
remaining_columns = df_cleaned.columns

# Display remaining columns with their index (starting index from 1)
print("\nRemaining columns after removing those with more than 90% missing values:")
print(f"{'Index':<6} {'Column Name':<50}")
for index, column in enumerate(remaining_columns, start=1):
    print(f"{index:<6} {column:<50}")

Remaining columns after removing those with more than 90% missing values:
Index  Column Name
1      case_id
2      case_submitter_id
3      project_id
4      age_at_index
5      days_to_birth
6      ethnicity
7      gender
8      race
9      vital_status
10     year_of_birth
11     age_at_diagnosis
12     classification_of_tumor
13     days_to_diagnosis
14     days_to_last_follow_up
15     figo_stage
16     icd_10_code
17     last_known_disease_status
18     morphology
19     primary_diagnosis
20     prior_malignancy
21     prior_treatment
22     progression_or_recurrence
23     site_of_resection_or_biopsy
24     synchronous_malignancy
25     tissue_or_organ_of_origin
26     tumor_grade
27     year_of_diagnosis
28     treatment_or_therapy
29     treatment_type

#New Data

In [129]:
print("Number of rows and columns:")
print(df_cleaned.shape)

Number of rows and columns:
(2175, 29)

In [132]:


# Optionally, print the shape of the new DataFrame to confirm
print(f"\nNew DataFrame with remaining columns has shape: {df_cleaned.shape}")

New DataFrame with remaining columns has shape: (2175, 29)

In [118]:
df_cleaned.head()

,case_id,case_submitter_id,project_id,age_at_index,days_to_birth,days_to_death,ethnicity,gender,race,vital_status,...,residual_disease,site_of_resection_or_biopsy,synchronous_malignancy,tissue_or_organ_of_origin,tumor_focality,tumor_grade,year_of_diagnosis,residual_disease.1,treatment_or_therapy,treatment_type
0,0014c2a8-850a-4305-a0d0-8a08b815a641,AD4306,FM-AD,NaN,NaN,NaN,not reported,female,not reported,Not Reported,...,NaN,"Uterus, NOS",NaN,"Uterus, NOS",NaN,Not Reported,NaN,NaN,NaN,NaN
1,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,-17045,NaN,not hispanic or latino,female,not reported,Alive,...,NaN,Endometrium,No,Endometrium,NaN,Not Reported,2009,NaN,no,"Pharmaceutical Therapy, NOS"
3,001e8d94-7884-4320-80f4-dbbac349394b,AD8086,FM-AD,NaN,NaN,NaN,not reported,female,not reported,Not Reported,...,NaN,"Uterus, NOS",NaN,"Colon, NOS",NaN,Not Reported,NaN,NaN,NaN,NaN
4,0020317d-d10e-4e75-8fa6-7c1bdcdee471,TCGA-HS-A5NA,TCGA-SARC,65,-24025,NaN,not reported,female,not reported,Alive,...,NaN,"Uterus, NOS",No,"Uterus, NOS",NaN,Not Reported,NaN,NaN,yes,"Radiation Therapy, NOS"
6,002724fa-7051-49fa-9c58-4bcb7eba4ac6,TCGA-BG-A0M6,TCGA-UCEC,73,-26666,671,not hispanic or latino,female,white,Dead,...,NaN,Endometrium,Not Reported,Endometrium,NaN,Not Reported,2008,NaN,yes,"Pharmaceutical Therapy, NOS"

In [133]:

# Initialize lists to store the column names based on their types
numerical_columns = []
categorical_columns = []

# Iterate through the remaining columns and classify them
for column in remaining_columns:
    if df_cleaned[column].dtype in ['int64', 'float64']:
        numerical_columns.append(column)
    elif df_cleaned[column].dtype == 'object':
        categorical_columns.append(column)

# Count the number of numerical and categorical columns
num_numerical = len(numerical_columns)
num_categorical = len(categorical_columns)

# Print the counts
print(f"Number of numerical columns: {num_numerical}")
print(f"Number of categorical columns: {num_categorical}")

# Display numerical columns
print("\nNumerical Columns:")
print(f"{'Index':<6} {'Column Name':<50}")
for index, column in enumerate(numerical_columns, start=1):
    print(f"{index:<6} {column:<50}")

# Display categorical columns
print("\nCategorical Columns:")
print(f"{'Index':<6} {'Column Name':<50}")
for index, column in enumerate(categorical_columns, start=1):
    print(f"{index:<6} {column:<50}")

Number of numerical columns: 0
Number of categorical columns: 29

Numerical Columns:
Index  Column Name

Categorical Columns:
Index  Column Name
1      case_id
2      case_submitter_id
3      project_id
4      age_at_index
5      days_to_birth
6      ethnicity
7      gender
8      race
9      vital_status
10     year_of_birth
11     age_at_diagnosis
12     classification_of_tumor
13     days_to_diagnosis
14     days_to_last_follow_up
15     figo_stage
16     icd_10_code
17     last_known_disease_status
18     morphology
19     primary_diagnosis
20     prior_malignancy
21     prior_treatment
22     progression_or_recurrence
23     site_of_resection_or_biopsy
24     synchronous_malignancy
25     tissue_or_organ_of_origin
26     tumor_grade
27     year_of_diagnosis
28     treatment_or_therapy
29     treatment_type

#**Target**

10     vital_status  
24     progression_or_recurrence  
30     treatment_or_therapy                              
31     treatment_type

In [134]:
# 1. Get the count of missing values for each column
missing_values = df_cleaned.isnull().sum()
total_rows = len(df_cleaned)  # Get the total number of rows

# 2. Identify columns with more than 70% missing values
columns_above_70_missing = missing_values[missing_values > 0.7 * total_rows]

# 3. Remove columns with more than 70% missing values
df_cleaned = df_cleaned.drop(columns=columns_above_70_missing.index)

# Display confirmation of removal
print(f"\nRemoved {len(columns_above_70_missing)} columns with more than 70% missing values.")

Removed 0 columns with more than 70% missing values.

##columns After Cleaning

In [135]:
# 4. Get the count of missing values for the cleaned DataFrame
missing_values_cleaned = df_cleaned.isnull().sum()

# Create a formatted output for remaining columns
print("\nMissing values count with percentage for remaining columns:")
print(f"{'Index':<6} {'Column Name':<50} {'Missing Values':<20} {'Percentage Missing':<20} {'Unique Values':<20}")

# 5. Display the count and percentage of missing values for each remaining column, along with the number of unique values
for index, column in enumerate(df_cleaned.columns):
    count_missing = missing_values_cleaned[column]
    percentage_missing = (count_missing / total_rows) * 100  # Calculate percentage
    unique_values_count = df_cleaned[column].nunique()  # Get the number of unique values
    print(f"{index + 1:<6} {column:<50} {count_missing:<20} {percentage_missing:<20.2f} {unique_values_count:<20}")

Missing values count with percentage for remaining columns:
Index  Column Name                                        Missing Values       Percentage Missing   Unique Values
1      case_id                                            0                    0.00                 2175
2      case_submitter_id                                  0                    0.00                 2175
3      project_id                                         0                    0.00                 11
4      age_at_index                                       970                  44.60                65
5      days_to_birth                                      741                  34.07                1368
6      ethnicity                                          0                    0.00                 4
7      gender                                             0                    0.00                 1
8      race                                               0                    0.00                 8
9      vital_status                                       0                    0.00                 4
10     year_of_birth                                      736                  33.84                70
11     age_at_diagnosis                                   31                   1.43                 2003
12     classification_of_tumor                            240                  11.03                4
13     days_to_diagnosis                                  981                  45.10                1
14     days_to_last_follow_up                             895                  41.15                1005
15     figo_stage                                         766                  35.22                18
16     icd_10_code                                        969                  44.55                8
17     last_known_disease_status                          19                   0.87                 4
18     morphology                                         0                    0.00                 34
19     primary_diagnosis                                  0                    0.00                 40
20     prior_malignancy                                   956                  43.95                3
21     prior_treatment                                    962                  44.23                2
22     progression_or_recurrence                          19                   0.87                 3
23     site_of_resection_or_biopsy                        0                    0.00                 8
24     synchronous_malignancy                             966                  44.41                3
25     tissue_or_organ_of_origin                          0                    0.00                 31
26     tumor_grade                                        16                   0.74                 6
27     year_of_diagnosis                                  739                  33.98                28
28     treatment_or_therapy                               961                  44.18                4
29     treatment_type                                     962                  44.23                6

In [136]:
print("Number of rows and columns:")
print(df_cleaned.shape)

Number of rows and columns:
(2175, 29)

##Second Dataset

In [139]:
!pip install openpyxl
import pandas as pd

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [140]:
# Load the data from the Excel file using the read_excel function with the appropriate engine
df2 = pd.read_excel('/content/Tableau-clinical.xlsx', engine='openpyxl')

In [141]:
# Display the first few rows of the dataframe
df2.head()

,case_id,case_submitter_id,project_id,age_at_index,age_is_obfuscated,cause_of_death,cause_of_death_source,country_of_birth,country_of_residence_at_enrollment,days_to_birth,...,treatment_dose_units,treatment_duration,treatment_effect,treatment_effect_indicator,treatment_frequency,treatment_intent_type,treatment_or_therapy,treatment_outcome,treatment_outcome_duration,treatment_type
0,0014c2a8-850a-4305-a0d0-8a08b815a641,AD4306,FM-AD,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
1,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,'--,'--,'--,'--,'--,-17045,...,'--,'--,'--,'--,'--,'--,no,'--,'--,"Pharmaceutical Therapy, NOS"
2,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,'--,'--,'--,'--,'--,-17045,...,'--,'--,'--,'--,'--,'--,no,'--,'--,"Radiation Therapy, NOS"
3,001e8d94-7884-4320-80f4-dbbac349394b,AD8086,FM-AD,'--,'--,'--,'--,'--,'--,'--,...,'--,'--,'--,'--,'--,'--,'--,'--,'--,'--
4,0020317d-d10e-4e75-8fa6-7c1bdcdee471,TCGA-HS-A5NA,TCGA-SARC,65,'--,'--,'--,'--,'--,-24025,...,'--,'--,'--,'--,'--,'--,yes,'--,'--,"Radiation Therapy, NOS"

In [142]:
print("Number of rows and columns:")
print(df2.shape)

Number of rows and columns:
(3465, 210)

#**Gene DataSet**

In [29]:
# Load the data from the Excel file using the read_excel function with the appropriate engine
df_gene = pd.read_excel('/content/gene expression.xlsx', engine='openpyxl')

In [143]:
# Display the first few rows of the dataframe
df_gene.head()

,case_submitter_id,SOCS1,LCP1,CD79A,PRF1,CD74,B2M,HLA-A,TNFRSF14,CDKN1A,...,MYCN,CCND2,ERBB2,ATP1A1,PCBP1,WNK2,FBLN2,ELN,FGFR3,ACKR3
0,TCGA-N1-A6IA,-0.767204,-0.461749,-0.332902,-0.257786,-0.842213,0.003660,-0.527104,-0.822228,-0.343772,...,-0.647902,-0.301046,-0.329624,0.543024,-0.939416,-0.921838,-0.203160,0.554093,-0.395300,-0.100925
1,HCM-CSHL-0810-C54,-0.930200,-0.346224,-0.325549,-0.405903,-0.980809,-0.918285,-0.566394,-1.011501,-0.269388,...,-0.636888,2.483832,0.193859,0.610308,-1.141286,-0.574715,-0.460560,-0.389508,1.119991,-0.739754
2,TCGA-A5-A2K3,3.187190,4.934528,10.272691,23.847947,2.032977,5.452049,2.996784,5.350055,-0.051616,...,-0.531504,0.216982,-0.213752,-1.296785,-1.072676,-0.141773,-0.404139,-0.366525,-0.238704,-0.567200
3,HTMCP-01-06-00146,0.385451,13.630531,18.445673,3.642983,0.493165,0.128107,-0.078765,0.141171,-0.628181,...,-0.645115,0.309929,-0.334493,-0.503471,-0.900339,-0.609958,-0.376637,-0.358543,-0.441127,-0.720948
4,TCGA-FI-A2CX,0.081907,13.989386,4.113545,7.251352,3.648098,5.218509,1.951937,3.250843,0.222748,...,-0.623766,0.244024,-0.325996,0.682222,0.508634,-0.758824,-0.490316,-0.381024,-0.025332,-0.332456

In [144]:
print("Number of rows and columns:")
print(df_gene.shape)

Number of rows and columns:
(1000, 101)

In [145]:
# Rename the column 'Case' to 'case_submitter_id' in the DataFrame df_gene
df_gene = df_gene.rename(columns={'Case': 'case_submitter_id'})

# Verify that the column name has been changed
df_gene.head()

,case_submitter_id,SOCS1,LCP1,CD79A,PRF1,CD74,B2M,HLA-A,TNFRSF14,CDKN1A,...,MYCN,CCND2,ERBB2,ATP1A1,PCBP1,WNK2,FBLN2,ELN,FGFR3,ACKR3
0,TCGA-N1-A6IA,-0.767204,-0.461749,-0.332902,-0.257786,-0.842213,0.003660,-0.527104,-0.822228,-0.343772,...,-0.647902,-0.301046,-0.329624,0.543024,-0.939416,-0.921838,-0.203160,0.554093,-0.395300,-0.100925
1,HCM-CSHL-0810-C54,-0.930200,-0.346224,-0.325549,-0.405903,-0.980809,-0.918285,-0.566394,-1.011501,-0.269388,...,-0.636888,2.483832,0.193859,0.610308,-1.141286,-0.574715,-0.460560,-0.389508,1.119991,-0.739754
2,TCGA-A5-A2K3,3.187190,4.934528,10.272691,23.847947,2.032977,5.452049,2.996784,5.350055,-0.051616,...,-0.531504,0.216982,-0.213752,-1.296785,-1.072676,-0.141773,-0.404139,-0.366525,-0.238704,-0.567200
3,HTMCP-01-06-00146,0.385451,13.630531,18.445673,3.642983,0.493165,0.128107,-0.078765,0.141171,-0.628181,...,-0.645115,0.309929,-0.334493,-0.503471,-0.900339,-0.609958,-0.376637,-0.358543,-0.441127,-0.720948
4,TCGA-FI-A2CX,0.081907,13.989386,4.113545,7.251352,3.648098,5.218509,1.951937,3.250843,0.222748,...,-0.623766,0.244024,-0.325996,0.682222,0.508634,-0.758824,-0.490316,-0.381024,-0.025332,-0.332456

In [146]:
df_cleaned.head()

,case_id,case_submitter_id,project_id,age_at_index,days_to_birth,ethnicity,gender,race,vital_status,year_of_birth,...,prior_malignancy,prior_treatment,progression_or_recurrence,site_of_resection_or_biopsy,synchronous_malignancy,tissue_or_organ_of_origin,tumor_grade,year_of_diagnosis,treatment_or_therapy,treatment_type
0,0014c2a8-850a-4305-a0d0-8a08b815a641,AD4306,FM-AD,NaN,NaN,not reported,female,not reported,Not Reported,NaN,...,NaN,NaN,not reported,"Uterus, NOS",NaN,"Uterus, NOS",Not Reported,NaN,NaN,NaN
1,001e0309-9c50-42b0-9e38-347883ee2cd3,TCGA-D1-A17N,TCGA-UCEC,46,-17045,not hispanic or latino,female,not reported,Alive,1963,...,no,No,not reported,Endometrium,No,Endometrium,Not Reported,2009,no,"Pharmaceutical Therapy, NOS"
3,001e8d94-7884-4320-80f4-dbbac349394b,AD8086,FM-AD,NaN,NaN,not reported,female,not reported,Not Reported,NaN,...,NaN,NaN,not reported,"Uterus, NOS",NaN,"Colon, NOS",Not Reported,NaN,NaN,NaN
4,0020317d-d10e-4e75-8fa6-7c1bdcdee471,TCGA-HS-A5NA,TCGA-SARC,65,-24025,not reported,female,not reported,Alive,NaN,...,no,No,not reported,"Uterus, NOS",No,"Uterus, NOS",Not Reported,NaN,yes,"Radiation Therapy, NOS"
6,002724fa-7051-49fa-9c58-4bcb7eba4ac6,TCGA-BG-A0M6,TCGA-UCEC,73,-26666,not hispanic or latino,female,white,Dead,1935,...,yes,No,not reported,Endometrium,Not Reported,Endometrium,Not Reported,2008,yes,"Pharmaceutical Therapy, NOS"

# **Merge**

In [148]:
# دمج البيانات
merged_df = pd.merge(df_gene, df_cleaned, on='case_submitter_id', how='inner')  # يمكنك تغيير نوع الدمج حسب الحاجة

merged_df.head()

,case_submitter_id,SOCS1,LCP1,CD79A,PRF1,CD74,B2M,HLA-A,TNFRSF14,CDKN1A,...,prior_malignancy,prior_treatment,progression_or_recurrence,site_of_resection_or_biopsy,synchronous_malignancy,tissue_or_organ_of_origin,tumor_grade,year_of_diagnosis,treatment_or_therapy,treatment_type
0,TCGA-N1-A6IA,-0.767204,-0.461749,-0.332902,-0.257786,-0.842213,0.003660,-0.527104,-0.822228,-0.343772,...,no,No,not reported,"Uterus, NOS",No,"Uterus, NOS",Not Reported,2011,no,"Pharmaceutical Therapy, NOS"
1,HCM-CSHL-0810-C54,-0.930200,-0.346224,-0.325549,-0.405903,-0.980809,-0.918285,-0.566394,-1.011501,-0.269388,...,no,No,NaN,Corpus uteri,NaN,"Uterus, NOS",Unknown,NaN,yes,"Surgery, NOS"
2,TCGA-A5-A2K3,3.187190,4.934528,10.272691,23.847947,2.032977,5.452049,2.996784,5.350055,-0.051616,...,no,No,not reported,Endometrium,No,Endometrium,Not Reported,2007,no,"Radiation Therapy, NOS"
3,HTMCP-01-06-00146,0.385451,13.630531,18.445673,3.642983,0.493165,0.128107,-0.078765,0.141171,-0.628181,...,no,No,NaN,"Uterus, NOS",No,"Hematopoietic system, NOS",NaN,2013,yes,Chemotherapy
4,TCGA-FI-A2CX,0.081907,13.989386,4.113545,7.251352,3.648098,5.218509,1.951937,3.250843,0.222748,...,yes,No,not reported,Endometrium,Not Reported,Endometrium,Not Reported,2008,no,"Pharmaceutical Therapy, NOS"

In [149]:
print(merged_df.shape)

(1000, 129)

In [150]:
# 4. Get the count of missing values for the cleaned DataFrame
missing_values_cleaned = merged_df.isnull().sum()

# Create a formatted output for remaining columns
print("\nMissing values count with percentage for remaining columns:")
print(f"{'Index':<6} {'Column Name':<50} {'Missing Values':<20} {'Percentage Missing':<20} {'Unique Values':<20}")

# 5. Display the count and percentage of missing values for each remaining column, along with the number of unique values
for index, column in enumerate(merged_df.columns):
    count_missing = missing_values_cleaned[column]
    percentage_missing = (count_missing / total_rows) * 100  # Calculate percentage
    unique_values_count = merged_df[column].nunique()  # Get the number of unique values
    print(f"{index + 1:<6} {column:<50} {count_missing:<20} {percentage_missing:<20.2f} {unique_values_count:<20}")

Missing values count with percentage for remaining columns:
Index  Column Name                                        Missing Values       Percentage Missing   Unique Values
1      case_submitter_id                                  0                    0.00                 1000
2      SOCS1                                              0                    0.00                 997
3      LCP1                                               0                    0.00                 999
4      CD79A                                              0                    0.00                 993
5      PRF1                                               0                    0.00                 989
6      CD74                                               0                    0.00                 1000
7      B2M                                                0                    0.00                 1000
8      HLA-A                                              0                    0.00                 1000
9      TNFRSF14                                           0                    0.00                 995
10     CDKN1A                                             0                    0.00                 1000
11     ID3                                                0                    0.00                 1000
12     LMO2                                               0                    0.00                 998
13     LEF1                                               0                    0.00                 998
14     AXIN2                                              0                    0.00                 994
15     CREB3L1                                            0                    0.00                 999
16     TENT5C                                             0                    0.00                 994
17     ALDH2                                              0                    0.00                 997
18     CDH1                                               0                    0.00                 999
19     TMPRSS2                                            0                    0.00                 973
20     ESR1                                               0                    0.00                 999
21     PIK3R1                                             0                    0.00                 998
22     TP53                                               0                    0.00                 1000
23     GATA2                                              0                    0.00                 994
24     FGFR2                                              0                    0.00                 998
25     MECOM                                              0                    0.00                 999
26     ERBB4                                              0                    0.00                 979
27     PREX2                                              0                    0.00                 985
28     MET                                                0                    0.00                 999
29     POU5F1                                             0                    0.00                 991
30     PAX8                                               0                    0.00                 1000
31     FGFR4                                              0                    0.00                 996
32     TFRC                                               0                    0.00                 1000
33     CDKN2C                                             0                    0.00                 994
34     CDKN1B                                             0                    0.00                 996
35     CCNE1                                              0                    0.00                 996
36     APOBEC3B                                           0                    0.00                 988
37     CXCR4                                              0                    0.00                 999
38     MYCL                                               0                    0.00                 994
39     NFIB                                               0                    0.00                 998
40     CEBPA                                              0                    0.00                 990
41     NDRG1                                              0                    0.00                 997
42     MYC                                                0                    0.00                 997
43     BCL9L                                              0                    0.00                 1000
44     WT1                                                0                    0.00                 982
45     BCL6                                               0                    0.00                 996
46     SLC34A2                                            0                    0.00                 987
47     MUC16                                              0                    0.00                 991
48     IGF2BP2                                            0                    0.00                 997
49     HMGA1                                              0                    0.00                 1000
50     TPM4                                               0                    0.00                 999
51     CDKN2A                                             0                    0.00                 1000
52     MLF1                                               0                    0.00                 996
53     SDHD                                               0                    0.00                 999
54     BTG2                                               0                    0.00                 1000
55     JUN                                                0                    0.00                 997
56     KLF6                                               0                    0.00                 1000
57     SGK1                                               0                    0.00                 994
58     BIRC3                                              0                    0.00                 994
59     TNFAIP3                                            0                    0.00                 997
60     PTK6                                               0                    0.00                 988
61     CBLC                                               0                    0.00                 982
62     MUC1                                               0                    0.00                 1000
63     ELF3                                               0                    0.00                 999
64     BCL3                                               0                    0.00                 1000
65     CARD11                                             0                    0.00                 987
66     ERBB3                                              0                    0.00                 998
67     MACC1                                              0                    0.00                 985
68     TBX3                                               0                    0.00                 988
69     FAT1                                               0                    0.00                 997
70     PTPN13                                             0                    0.00                 989
71     TNC                                                0                    0.00                 999
72     PRRX1                                              0                    0.00                 993
73     MLLT11                                             0                    0.00                 992
74     CHST11                                             0                    0.00                 992
75     SFRP4                                              0                    0.00                 999
76     HOXA11                                             0                    0.00                 882
77     FSTL3                                              0                    0.00                 993
78     CSF1R                                              0                    0.00                 997
79     SIRPA                                              0                    0.00                 999
80     PDGFRA                                             0                    0.00                 993
81     MAF                                                0                    0.00                 991
82     MAFB                                               0                    0.00                 999
83     PDGFRB                                             0                    0.00                 997
84     COL3A1                                             0                    0.00                 1000
85     COL1A1                                             0                    0.00                 1000
86     CDH11                                              0                    0.00                 995
87     CCND1                                              0                    0.00                 1000
88     ETV4                                               0                    0.00                 998
89     ETV5                                               0                    0.00                 998
90     SIX1                                               0                    0.00                 987
91     FGFR1                                              0                    0.00                 999
92     MYCN                                               0                    0.00                 990
93     CCND2                                              0                    0.00                 997
94     ERBB2                                              0                    0.00                 999
95     ATP1A1                                             0                    0.00                 1000
96     PCBP1                                              0                    0.00                 997
97     WNK2                                               0                    0.00                 992
98     FBLN2                                              0                    0.00                 997
99     ELN                                                0                    0.00                 998
100    FGFR3                                              0                    0.00                 990
101    ACKR3                                              0                    0.00                 998
102    case_id                                            0                    0.00                 1000
103    project_id                                         0                    0.00                 7
104    age_at_index                                       14                   0.64                 60
105    days_to_birth                                      14                   0.64                 962
106    ethnicity                                          0                    0.00                 3
107    gender                                             0                    0.00                 1
108    race                                               0                    0.00                 6
109    vital_status                                       0                    0.00                 3
110    year_of_birth                                      14                   0.64                 67
111    age_at_diagnosis                                   19                   0.87                 958
112    classification_of_tumor                            0                    0.00                 3
113    days_to_diagnosis                                  18                   0.83                 1
114    days_to_last_follow_up                             110                  5.06                 744
115    figo_stage                                         41                   1.89                 17
116    icd_10_code                                        6                    0.28                 8
117    last_known_disease_status                          11                   0.51                 1
118    morphology                                         0                    0.00                 16
119    primary_diagnosis                                  0                    0.00                 17
120    prior_malignancy                                   1                    0.05                 3
121    prior_treatment                                    6                    0.28                 2
122    progression_or_recurrence                          11                   0.51                 1
123    site_of_resection_or_biopsy                        0                    0.00                 8
124    synchronous_malignancy                             10                   0.46                 3
125    tissue_or_organ_of_origin                          0                    0.00                 8
126    tumor_grade                                        8                    0.37                 3
127    year_of_diagnosis                                  16                   0.74                 23
128    treatment_or_therapy                               5                    0.23                 3
129    treatment_type                                     6                    0.28                 6

# **Handle Missing Values**

# **Get all column names as a list**

###treatment_anatomic_site

In [33]:
# Define the column name in a variable
column_name = 'vital_status'

# Get the unique values in the column
unique_values = df[column_name].unique()
print("Unique values:")
print(unique_values)

# Count the occurrences of each unique value
value_counts = df[column_name].value_counts()
print("\nValue counts:")
print(value_counts)

# Get the number of unique values
num_unique = df[column_name].nunique()
print("\nNumber of unique values:")
print(num_unique)

# Get the total number of values in the column (including duplicates)
total_count = len(df[column_name])
print("\nTotal number of values:")
print(total_count)

# Count the number of NaN (Not a Number) values
nan_count = df[column_name].isnull().sum()
print("\nNumber of NaN values:")
print(nan_count)

Unique values:
['Not Reported' 'Alive' 'Dead' 'Unknown']

Value counts:
vital_status
Alive           1726
Dead             997
Not Reported     732
Unknown           10
Name: count, dtype: int64

Number of unique values:
4

Total number of values:
3465

Number of NaN values:
0

###treatment_or_therapy

In [34]:
# Define the column name in a variable
column_name = 'treatment_or_therapy'

# Get the unique values in the column
unique_values = df[column_name].unique()
print("Unique values:")
print(unique_values)

# Count the occurrences of each unique value
value_counts = df[column_name].value_counts()
print("\nValue counts:")
print(value_counts)

# Get the number of unique values
num_unique = df[column_name].nunique()
print("\nNumber of unique values:")
print(num_unique)

# Get the total number of values in the column (including duplicates)
total_count = len(df[column_name])
print("\nTotal number of values:")
print(total_count)

# Count the number of NaN (Not a Number) values
nan_count = df[column_name].isnull().sum()
print("\nNumber of NaN values:")
print(nan_count)

Unique values:
[nan 'no' 'yes' 'not reported' 'unknown']

Value counts:
treatment_or_therapy
no              1216
yes             1178
not reported      95
unknown            6
Name: count, dtype: int64

Number of unique values:
4

Total number of values:
3465

Number of NaN values:
970

##**Identify the column contents**

In [126]:
import pandas as pd

def analyze_column(df_cleaned, column_name):
    # Get the unique values in the column
    unique_values = df_cleaned[column_name].unique()
    print("Unique values:")
    print(unique_values)

    # Count the occurrences of each unique value
    value_counts = df_cleaned[column_name].value_counts()
    print("\nValue counts:")
    print(value_counts)

    # Get the number of unique values
    num_unique = df_cleaned[column_name].nunique()
    print("\nNumber of unique values:")
    print(num_unique)

    # Get the total number of values in the column (including duplicates)
    total_count = len(df_cleaned[column_name])
    print("\nTotal number of values:")
    print(total_count)

    # Count the number of NaN (Not a Number) values
    nan_count = df_cleaned[column_name].isnull().sum()
    print("\nNumber of NaN values:")
    print(nan_count)

# Example usage
# df = pd.DataFrame(...)  # استبدل هذه السطر بإنشاء DataFrame الخاص بك
# analyze_column(df, 'vital_status')

In [128]:
column_name = input("Please enter a column name: ")
analyze_column(df_cleaned, column_name)

Please enter a column name: treatment_type
Unique values:
[nan 'Pharmaceutical Therapy, NOS' 'Radiation Therapy, NOS' 'Chemotherapy'
 'Targeted Molecular Therapy' 'Immunotherapy (Including Vaccines)'
 'Surgery, NOS']

Value counts:
treatment_type
Pharmaceutical Therapy, NOS           614
Radiation Therapy, NOS                592
Chemotherapy                            4
Targeted Molecular Therapy              1
Immunotherapy (Including Vaccines)      1
Surgery, NOS                            1
Name: count, dtype: int64

Number of unique values:
6

Total number of values:
2175

Number of NaN values:
962

In [35]:
# Define the column name in a variable
column_name = 'treatment_or_therapy'

# Get the unique values in the column
unique_values = df[column_name].unique()
print("Unique values:")
print(unique_values)

# Count the occurrences of each unique value
value_counts = df[column_name].value_counts()
print("\nValue counts:")
print(value_counts)

# Get the number of unique values
num_unique = df[column_name].nunique()

# Get the total number of values in the column (including duplicates)
total_count = len(df[column_name])

# Count the number of NaN (Not a Number) values
nan_count = df[column_name].isnull().sum()

# Display the results in a formatted way
print("\nNumber of unique values:      Total number of values:       Number of NaN values:")
print(f"{num_unique:<30} {total_count:<30} {nan_count}")

Unique values:
[nan 'no' 'yes' 'not reported' 'unknown']

Value counts:
treatment_or_therapy
no              1216
yes             1178
not reported      95
unknown            6
Name: count, dtype: int64

Number of unique values:      Total number of values:       Number of NaN values:
4                              3465                           970

#d

In [42]:
import pandas as pd

# Assume you have a DataFrame named df
# df = pd.read_csv('your_file.csv')  # Read data from a CSV file, for example

# Extract columns of type object
object_columns = df.select_dtypes(include=['object'])

# Get the names of the object columns
object_column_names = object_columns.columns.tolist()

# Display the names of the object columns with their unique value counts
print(f"{'Column Number':<15} {'Name Columns':<40} {'Unique values count':<25}")
print('-' * 80)  # Print a separator line
for index, column in enumerate(object_column_names, start=1):
    unique_count = df[column].nunique()  # Count unique values in the column
    print(f"{index:<15} {column:<40} {unique_count:<25}")  # Align the text in columns

Column Number   Name Columns                             Unique values count
--------------------------------------------------------------------------------
1               case_id                                  2175
2               case_submitter_id                        2175
3               project_id                               11
4               age_at_index                             65
5               age_is_obfuscated                        2
6               cause_of_death                           5
7               days_to_birth                            1368
8               days_to_death                            446
9               ethnicity                                4
10              gender                                   1
11              race                                     8
12              vital_status                             4
13              year_of_birth                            70
14              year_of_death                            27
15              age_at_diagnosis                         2004
16              ajcc_clinical_m                          5
17              ajcc_pathologic_m                        4
18              ajcc_pathologic_n                        7
19              ajcc_pathologic_stage                    15
20              ajcc_pathologic_t                        8
21              ajcc_staging_system_edition              4
22              ann_arbor_b_symptoms                     2
23              ann_arbor_clinical_stage                 1
24              ann_arbor_extranodal_involvement         1
25              ann_arbor_pathologic_stage               3
26              best_overall_response                    2
27              burkitt_lymphoma_clinical_variant        3
28              classification_of_tumor                  4
29              days_to_best_overall_response            6
30              days_to_diagnosis                        1
31              days_to_last_follow_up                   1005
32              days_to_last_known_disease_status        203
33              days_to_recurrence                       15
34              figo_stage                               18
35              icd_10_code                              8
36              last_known_disease_status                4
37              laterality                               2
38              metastasis_at_diagnosis                  3
39              method_of_diagnosis                      5
40              morphology                               34
41              ovarian_specimen_status                  1
42              ovarian_surface_involvement              1
43              peritoneal_fluid_cytological_status      2
44              primary_diagnosis                        40
45              prior_malignancy                         3
46              prior_treatment                          2
47              progression_or_recurrence                3
48              residual_disease                         4
49              site_of_resection_or_biopsy              8
50              synchronous_malignancy                   3
51              tissue_or_organ_of_origin                31
52              tumor_focality                           2
53              tumor_grade                              6
54              year_of_diagnosis                        28
55              days_to_treatment_end                    21
56              days_to_treatment_start                  21
57              initial_disease_status                   3
58              number_of_cycles                         2
59              regimen_or_line_of_therapy               3
60              residual_disease.1                       4
61              therapeutic_agents                       18
62              treatment_intent_type                    2
63              treatment_or_therapy                     4
64              treatment_outcome                        3
65              treatment_type                           10

##age_at_diagnosis

In [37]:


# Now you can proceed with your code:
# Let's say your 'age_at_diagnosis' column is in days
# Convert age from days to years (considering 1 year = 365.25 days)
df['age_at_diagnosis_years'] = df['age_at_diagnosis'] / 365.25

# Display the updated DataFrame
print(df[['age_at_diagnosis', 'age_at_diagnosis_years']])

TypeError: unsupported operand type(s) for /: 'str' and 'float'